name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: u601252444_aphaQ
          MYSQL_USER: u601252444_liBjG
          MYSQL_PASSWORD: Waz5GDGnUU
        options: >-
          --health-cmd="mysqladmin ping -h127.0.0.1 -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v4

    - uses: shivammathur/setup-php@v2
      with:
        php-version: '^8.1'

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Set Laravel DB config
      run: |
        echo "DB_CONNECTION=mysql" >> .env
        echo "DB_HOST=127.0.0.1" >> .env
        echo "DB_PORT=3306" >> .env
        echo "DB_DATABASE=u601252444_aphaQ" >> .env
        echo "DB_USERNAME=u601252444_liBjG" >> .env
        echo "DB_PASSWORD=Waz5GDGnUU" >> .env

    - name: Install Dependencies
      run: composer install --no-interaction --prefer-dist

    - name: Generate key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 775 storage bootstrap/cache

    - name: Create Storage Symlink
      run: php artisan storage:link

    - name: Wait for MySQL
      run: |
        until mysqladmin ping -h127.0.0.1 -u u601252444_liBjG -pWaz5GDGnUU --silent; do
          echo "Waiting for MySQL..."
          sleep 3
        done

    - name: Run Migrations & Seed
      run: php artisan migrate:fresh --seed

    - name: Execute tests (Unit and Feature tests)
      run: php artisan test
